language: python
sudo: false
env:
  global:
    - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  # install a few of the dependencies that pip would otherwise try to install
  # when intalling scikit-bio
  - travis_retry conda create --yes -n boatymcboatface python=$PYTHON_VERSION pip
    nose flake8 libgfortran 'pandas>=0.18' 'matplotlib>=1.1.0' 'scipy>0.13.0'
    'numpy>=1.7'
  - source activate boatymcboatface
  - travis_retry pip install .
  - 'echo "backend: Agg" > matplotlibrc'
script:
  - nosetests --with-coverage
after_success:
  - coveralls
